# roles/common/tasks/disable_noisy_timers.yml
---
# Welche Timer sicher abschalten?
- set_fact:
    noisy_timers_default:
      - apt-daily.timer
      - apt-daily-upgrade.timer
      - man-db.timer
      - plocate-updatedb.timer
      - mlocate.timer
      - updatedb.timer
      - fwupd-refresh.timer
      - e2scrub_all.timer
      - e2scrub_reap.timer
      - motd-news.timer
      - snapd.snap-repair.timer
    disable_fstrim: false     # auf true setzen, wenn ihr fstrim nicht braucht
    disable_logrotate: false  # auf true setzen, wenn ihr logrotate-Timer auch aus wollt

- name: Build final timer list
  set_fact:
    timers_to_disable: >-
      {{
        noisy_timers_default
        + (['fstrim.timer'] if disable_fstrim else [])
        + (['logrotate.timer'] if disable_logrotate else [])
      }}

# Falls es Timer gibt, die auf deiner VM nicht existieren: einfach ignorieren
- name: Stop + disable + mask timers (idempotent)
  block:
    - name: Stop timer if running
      systemd:
        name: "{{ item }}"
        state: stopped
      failed_when: false
      loop: "{{ timers_to_disable }}"

    - name: Disable timer at boot
      systemd:
        name: "{{ item }}"
        enabled: false
      failed_when: false
      loop: "{{ timers_to_disable }}"

    - name: Mask timer to prevent activation
      systemd:
        name: "{{ item }}"
        masked: true
      failed_when: false
      loop: "{{ timers_to_disable }}"

    # Optional: zugehörige Services ebenfalls deaktivieren
    - name: Disable related services (best effort)
      systemd:
        name: "{{ item | regex_replace('\\.timer$', '.service') }}"
        enabled: false
        state: stopped
      failed_when: false
      loop: "{{ timers_to_disable }}"
  notify: systemd-daemon-reload

- name: Ensure journald is memory-only (reduziert Disk-I/O weiter)
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^#?Storage='
    line: 'Storage=volatile'
  notify: restart journald

# nach dem großen Block einmal systemd reload triggern
- name: Trigger systemd daemon-reload
  meta: flush_handlers